### PR TITLE
Adding Salesforce Account table to filter out paid customers

### PR DESCRIPTION
**Pull request by sri-byte**
Hi, 

Adding Salesforce Account table. 

Impact - 
1) Salesforce Account table contains information about paying customers. As per request, we need to filter out these customers from the dashboard.
2) Tested the changes locally on Snowflake, and the filter works as expected.

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]

**Comment by jasonblais** [comment]
@sri-byte Thank you! Changes look good.

It doesn't look like I'm an approved reviewer, so you may need to request a review from Catalin or Nick, in order for this to be merged.

**Comment by sri-byte** [comment]
I'm unable to add reviewers in this project.

**Comment by jasonblais** [comment]
@sri-byte I see .. @catalintomai / @nickmisasi neither of us are able to add reviewers or approve changes, wondering if one of you have the privileges to review/approve, then merge?

**Review by catalintomai — APPROVED** [review]

**Comment by catalintomai** [comment]
> I'm unable to add reviewers in this project.

@amyblais - do you know what is the process for assigning these permissions to @sri-byte? Thanks.

**Comment by amyblais** [comment]
> > I'm unable to add reviewers in this project.
> 
> @amyblais - do you know what is the process for assigning these permissions (add reviewers, merge, etc.) to @sri-byte? Thanks.

You can post about it at the [DevOps channel](https://community.mattermost.com/core/channels/build) and either Carlos or Spiros can help.

**Comment by catalintomai** [comment]
> > > I'm unable to add reviewers in this project.
> > 
> > 
> > @amyblais - do you know what is the process for assigning these permissions (add reviewers, merge, etc.) to @sri-byte? Thanks.
> 
> You can post about it at the [DevOps channel](https://community.mattermost.com/core/channels/build) and either Carlos or Spiros can help.

Thanks.

**Comment by catalintomai** [comment]
> > > I'm unable to add reviewers in this project.
> > 
> > 
> > @amyblais - do you know what is the process for assigning these permissions (add reviewers, merge, etc.) to @sri-byte? Thanks.
> 
> You can post about it at the [DevOps channel](https://community.mattermost.com/core/channels/build) and either Carlos or Spiros can help.

@sri-byte , please make the permissions request in the channel - don't think it is necessary, but cc me and/or Jason as sponsors if necessary.

**Comment by nickmisasi** [comment]
@sri-byte would you like me to merge this while you get permissions sorted out?

**Pull request merged**
